import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
export default function Home() {
  return (
    <>
      <Head>
        <title>Anna Schierholz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10">
        <section className="bg-slate-500 min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl ml-8">Annas coole Website</h1>
            <ul className="flex items-center">
              <li><BsFillMoonStarsFill className="cursor-pointer text-2xl"/></li>
              <li>
                <a className="bg-gradient-to-r from-yellow-500 to-orange-700 text-white px-4 py-2 rounded-2xl ml-8 mr-8" href="https://www.linkedin.com/in/anna-schierholz/">LinkedIn</a>
                </li>
            </ul>
          </nav>
        </section>
      </main>
    </>
  )
}
