import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillLinkedin, AiFillGithub} from 'react-icons/ai'
import Image from "next/legacy/image"
import anna from "../../public/dev-ed-wave.png"
import design from "../../public/design.png"
import erasmus from "../../public/erasmus_viz.png"
import code from "../../public/code.png"
import {useState} from "react";
export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <>
    <div className={darkMode ? 'dark' : ""}>
      <Head>
        <title>Anna Schierholz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-slate-900">
        <section className="bg-white min-h-screen dark:bg-slate-900">
          <nav className=" py-10 mb-12 flex justify-between">
            <h1 className="text-xl ml-8 font-raleway dark:text-white">Anna Schierholz</h1>
            <ul className="flex items-center">
              <li><BsFillMoonStarsFill onClick={()=> setDarkMode(!darkMode)} className="dark:text-white cursor-pointer text-2xl "/></li>
              <li>
                <a className="bg-gradient-to-r from-purple-800 to-purple-500 text-white px-4 py-2 rounded-2xl ml-8 mr-8 dark:text-white" href="https://www.annalogie.com/">Blog</a>
                </li>
            </ul>
          </nav>
          <div className="text-center p-10 ">
            <h2 className='font-raleway text-5xl py-2 text-purple-700 md:text-6xl '>
              Anna Schierholz
            </h2>
            <h3 className= "font-raleway text-2xl py-2 md:text-3xl dark:text-white">
              Problem solver, Creative and Enthusiast
            </h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-l mx-auto dark:text-white'>
              Moin! I'm Anna from Hamburg and I'm currently a M.Sc. Computer Science student at Aarhus University. <br /> Have a look around to see what I'm up to!
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-white">
              <a href="https://www.linkedin.com/in/anna-schierholz/"><AiFillLinkedin/></a> 
              <a href="https://github.com/annalogie-create"><AiFillGithub/></a> 
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-purple-800 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
            <Image src={anna} fill="fill" className='object-cover'/>
          </div>
        </section>
        {/* Card System */}
        <section>
          <div >
            <h3 className="text-3xl py-1 dark:text-white">
              Projects
            </h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>
              I have done several projects in- and outside of university. In my Master's degree, I was focusing on Data Science and Human Computer Interaction and am now writing my Master thesis in <span className='text-purple-800'>Data Visualization</span>.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className='text-center content-center shadow-lg p-10 rounded-xl my-10 bg-purple-100 dark:bg-purple-900'>
              <Image className="align-middle"src={design} width={100} height={100}/>
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white">Illustration</h3>
              <p className='dark:text-white'>
              Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
              </p>
              <h4 className='text-purple-800 py-4 dark:text-purple-200'>Illustration tools I use</h4>
              <p className='text-gray-800 py-1 dark:text-white'>Krita</p>
              <p className='text-gray-800 py-1 dark:text-white'>Procreate</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 bg-purple-100 dark:bg-purple-900'>
              <Image src={code} width={100} height={100}/>
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white">Coding</h3>
              <p className='dark:text-white'>
              Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
              </p>
              <h4 className='text-purple-800 py-4 dark: text-purple-200'>Languages I use</h4>
              <p className='text-gray-800 py-1 dark:text-white'>Python</p>
              <p className='text-gray-800 py-1 dark:text-white'>Javascript/Typescript</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-white'>Portfolio</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>
              I have done several projects in- and outside of university. In my Master's degree, I was focusing on Data Science and Human Computer Interaction and am now writing my Master thesis in <span className='text-purple-800'>Data Visualization</span>.
            </p>
          </div >
          <div  className="flex gap-10 py-10 lg: flex-row lg:flex-wrap">
            <div className='basis-1/3 flex-1'>
              <div><Image src={erasmus} className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive"/></div>
            </div>
            <div className='basis-1/3 flex-1'>
              <div><Image src={erasmus} className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive"/></div>
            </div>
            <div className='basis-1/3 flex-1'>
              <div><Image src={erasmus} className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive"/></div>
            </div>
            <div className='basis-1/3 flex-1'>
              <div><Image src={erasmus} className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive"/></div>
            </div>
          </div>
        </section>
      </main>
      </div>
    </>
  )
}
